name: Taller 1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert ipykernel
        python -m ipykernel install --user --name=python3

    - name: Configuración de tests
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/id_ed25519 << 'EOF'
        ${{ secrets.TEST_OCULTOS }}
        EOF
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Descarga de tests
      run: |
        git clone git@github.com:Procesamiento-de-Lenguaje-Natural/test-privado-taller1.git temp_repo
        mkdir -p tests_privados/ejercicio1
        cp temp_repo/test_1.py tests_privados/ejercicio1/test_1.py 2>/dev/null || echo "test_1.py no encontrado"
        rm -rf temp_repo

    - name: Ejecución notebook ejercicio1
      run: |
        jupyter nbconvert --to notebook --execute notebooks/ejercicio1.ipynb --output ejercicio1_out.ipynb --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=300

    - name: Verificación test_1 ejercicio1
      run: |
        pytest tests_privados/ejercicio1/test_1.py -v