name: Taller 1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert ipykernel
        python -m ipykernel install --user --name=python3

    - name: Configuración de tests
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/id_ed25519 << 'EOF'
        ${{ secrets.TEST_OCULTOS }}
        EOF
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Descarga de tests
      run: |
        git clone git@github.com:Procesamiento-de-Lenguaje-Natural/test-privado-taller1.git temp_repo
        mkdir -p tests_descargados
        cp temp_repo/test_1.py tests_descargados/test_1.py 2>/dev/null || echo "test_1.py no encontrado"
        cp temp_repo/test_2.py tests_descargados/test_2.py 2>/dev/null || echo "test_2.py no encontrado"
        rm -rf temp_repo

    - name: Debug - Ver contenido del test_2 descargado
      run: |
        echo "=== Contenido del test_2.py descargado ==="
        cat tests_descargados/test_2.py
        echo "=== Fin del contenido ==="

    - name: Ejecución notebook ejercicio1
      run: |
        jupyter nbconvert --to notebook --execute notebooks/ejercicio1.ipynb --output ejercicio1_out.ipynb --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=300 --ExecutePreprocessor.allow_errors=true

    - name: Debug - Ver archivos generados
      run: |
        echo "=== Archivos en directorio raíz ==="
        ls -la *.ipynb
        echo "=== Archivos en notebooks/ ==="
        ls -la notebooks/

    - name: Verificación test_1 ejercicio1
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)/data pytest tests_descargados/test_1.py -v

    - name: Verificación test_2 ejercicio1 con debug
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)/data pytest tests_descargados/test_2.py -v -s